#!/bin/bash

set -e
./clean
cd toboot
make
cd ../booster
make
gcc make-booster.c -o make-booster
chmod +x make-booster
./make-booster ../toboot/toboot.bin toboot-booster.bin
cp toboot-booster.bin toboot-booster.dfu
dfu-suffix --pid 0x70b1 --vid 0x1209 --add toboot-booster.dfu
